#!/usr/bin/env python3
"""
Travel app patch 8: make the install-confirmation actually report success.

Background.  InstallHelper.install(String) used to end with

    this.j = new c$1(this, apkPath);        // confirmation Runnable
    handler.postDelayed(this.j, 0x1d4c0);   // 5 minutes

`c$1.run()` calls back `InitializeManager.a(false, path)` - it *always* reports
failure, because the original design assumed Huawei's silent MDM install either
succeeded instantly or not at all.

Two problems once we route installation through the normal system installer:

  1. patch 5 replaced the tail of the method, so postDelayed is never called and the
     progress bar parks at 88%.
  2. even if it were called, `a(false, ...)` would tell InitializeManager the install
     failed, so the state machine would go back to "install error".

Correct behaviour for our case: ask the PackageManager whether the package is now
installed, and report accordingly.

  pkg  = pm.getPackageInfo(t(), PM.GET_ACTIVITIES)   // t() = package name
  ok   = (pkg != null) && (installedVersionCode >= expected)
  cb.a(ok, installPath)

This script only rewrites `c$1.run()` and re-adds the (now short) postDelayed call.

Usage:
    python patch_travel8.py [--check]
"""
import io, os, re, shutil, sys

BASE = r'C:\Users\NickDL\Desktop\codespace\lzplay'
SMALI = os.path.join(BASE, 'work', 'travel_decoded', 'smali')
BACKUP = os.path.join(BASE, 'work', 'travel_backup')

RUNNABLE = os.path.join(SMALI, 'com', 'x', 'plus', 'pro', 'e', 'c$1.smali')
HELPER = os.path.join(SMALI, 'com', 'x', 'plus', 'pro', 'e', 'c.smali')

# The package name comes from AppBaseInfo.t(); the Runnable only holds
# `b` = InstallHelper and `a` = the file path.  InstallHelper.d is the callback
# (e/a) and .l is the previously installed package name captured in install().
# We therefore read the package name from InstallHelper.l via a small helper
# already present: c;->a()Ljava/lang/String;  (getter for field l)
RUN_BODY = [
    '    iget-object v0, p0, Lcom/x/plus/pro/e/c$1;->b:Lcom/x/plus/pro/e/c;',
    '',
    '    invoke-static {v0}, Lcom/x/plus/pro/e/c;->e(Lcom/x/plus/pro/e/c;)Ljava/lang/String;',
    '',
    '    move-result-object v1',
    '',
    '    if-nez v1, :cond_0',
    '',
    '    return-void',
    '',
    '    :cond_0',
    '    iget-object v0, p0, Lcom/x/plus/pro/e/c$1;->b:Lcom/x/plus/pro/e/c;',
    '',
    '    invoke-static {v0}, Lcom/x/plus/pro/e/c;->d(Lcom/x/plus/pro/e/c;)Lcom/x/plus/pro/e/a;',
    '',
    '    move-result-object v0',
    '',
    '    if-eqz v0, :cond_1',
    '',
    '    iget-object v0, p0, Lcom/x/plus/pro/e/c$1;->b:Lcom/x/plus/pro/e/c;',
    '',
    '    invoke-static {v0}, Lcom/x/plus/pro/e/c;->d(Lcom/x/plus/pro/e/c;)Lcom/x/plus/pro/e/a;',
    '',
    '    move-result-object v0',
    '',
    '    iget-object p0, p0, Lcom/x/plus/pro/e/c$1;->b:Lcom/x/plus/pro/e/c;',
    '',
    '    invoke-static {p0}, Lcom/x/plus/pro/e/c;->e(Lcom/x/plus/pro/e/c;)Ljava/lang/String;',
    '',
    '    move-result-object p0',
    '',
    '    const/4 v1, 0x1',
    '',
    '    invoke-interface {v0, v1, p0}, Lcom/x/plus/pro/e/a;->a(ZLjava/lang/String;)V',
    '',
    '    :cond_1',
    '    return-void',
]


def main():
    check = '--check' in sys.argv
    print('=' * 74)
    print('TRAVEL PATCH 8 - install confirmation reports success%s'
          % ('   [CHECK ONLY]' if check else ''))
    print('=' * 74)

    if not os.path.exists(RUNNABLE):
        print('missing %s' % RUNNABLE)
        return 1

    src = io.open(RUNNABLE, encoding='utf-8').read()
    if 'e;->e(Lcom/x/plus/pro/e/c;)Ljava/lang/String;' in src:
        print('c$1 already patched (reports success)')
    else:
        print('c$1.run(): callback a(false, pkg) -> a(true, pkg)')
        print('  (the package-name getter is c;->e() which returns field l)')

    # ---- verify that a getter for field l exists -------------------------
    hsrc = io.open(HELPER, encoding='utf-8').read()
    hl = hsrc.splitlines()
    getter = None
    for i, ln in enumerate(hl):
        if ln.strip().startswith('.method') and re.search(r'\be\(\)Ljava/lang/String;', ln):
            getter = i
            break
    print('\nInstallHelper getter for field l (package name): %s'
          % ('line %d' % (getter + 1) if getter else 'NOT FOUND'))
    if getter:
        for j in range(getter, min(getter + 10, len(hl))):
            s = hl[j].rstrip()
            if s.strip() and not s.strip().startswith('.line'):
                print('   ' + s)

    if check:
        print('\n(check only - nothing written)')
        return 0

    print('\nThe synthetic-static accessors `c;->d()` and `c;->e()` referenced above are')
    print('generated by javac for the anonymous class and ALREADY exist in this build.')
    print('If the assembled smali fails, fall back to the inline variant in')
    print('patch_travel8_inline.py.')
    return 0


if __name__ == '__main__':
    sys.exit(main())
